info:
  contact: {}
  description: gin-base-framework Server api
  license: {}
  termsOfService: https://github.com/itcloudy
  title: gin-base-framework Server api
  version: "2.0"
paths:
  /auth/banner_group:
    post:
      consumes:
      - application/json
      description: 用户用户openid
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 微信Code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{}'
          schema:
            type: string
      summary: 用户用户openid
      tags:
      - 微信
  /auth/image_upload:
    post:
      consumes:
      - multipart/form-data
      description: 图片上传
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 上传文件
        in: query
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 图片上传
      tags:
      - 通用
  /auth/menu/{id}:
    delete:
      consumes:
      - application/json
      description: 菜单删除
      parameters:
      - description: 菜单ID
        in: path
        name: id
        required: true
        type: integer
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":null,"message":"success"}'
          schema:
            type: string
      summary: 菜单删除
      tags:
      - 菜单
    get:
      consumes:
      - application/json
      description: 菜单获得
      parameters:
      - description: 菜单获得ID
        in: path
        name: id
        required: true
        type: integer
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      summary: 菜单获得
      tags:
      - 菜单
    put:
      consumes:
      - application/json
      description: 菜单修改
      parameters:
      - description: 轮播图组ID
        in: path
        name: id
        required: true
        type: integer
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 是否有效
        in: query
        name: active
        required: true
        type: boolean
      - description: 开始时间
        in: query
        name: start_date
        required: true
        type: time
      - description: 结束时间
        in: query
        name: end_date
        required: true
        type: time
      - description: 轮播组名称
        in: query
        name: name
        required: true
        type: string
      - description: 轮播时间间隔(s)
        in: query
        name: display_time
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"parent_id":0,"name":"测试修改","route":"route-system","component":"SystemComponent","icon":"system-icon","sequence":1},"message":"success"}'
          schema:
            type: string
      summary: 菜单修改
      tags:
      - 菜单
  /auth/menutree:
    get:
      consumes:
      - application/json
      description: 系统菜单树,系统管理员才可用
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":[{"id":1,"parent_id":0,"name":"系统设置","route":"route-system","component":"SystemComponent","icon":"system-icon","sequence":1,"children":[{"id":2,"parent_id":1,"name":"系统用户","route":"/system/user","icon":"system-user","sequence":1}]},{"id":3,"parent_id":0,"name":"分类模块","route":"route_modyle","component":"Module","icon":"module","sequence":2,"children":[{"id":4,"parent_id":3,"name":"模块列表","route":"/auth/category","icon":"category","sequence":1}]},{"id":5,"parent_id":0,"name":"公司管理","route":"route_company","component":"Company","icon":"company","sequence":2,"children":[{"id":6,"parent_id":5,"name":"公司分类","route":"route_company_1","component":"Company","icon":"company","sequence":2,"children":[{"id":7,"parent_id":6,"name":"一级公司","route":"route_company_2","component":"Company","icon":"company","sequence":2},{"id":8,"parent_id":6,"name":"二级公司","route":"route_company_3","component":"Company","icon":"company","sequence":2}]}]}],"message":"success"}}'
          schema:
            type: string
      summary: 系统菜单树
      tags:
      - 菜单
  /auth/pay/wxapp:
    post:
      consumes:
      - application/json
      description: 微信支付
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 费用（分
        in: query
        name: total_fee
        required: true
        type: integer
      - description: 币种
        in: query
        name: fee_type
        required: true
        type: string
      - description: 公司等级
        in: query
        name: level
        required: true
        type: integer
      - description: 购买月数
        in: query
        name: month
        required: true
        type: integer
      - description: 公司编号
        in: query
        name: request_no
        required: true
        type: string
      - description: 微信openid
        in: query
        name: open_id
        required: true
        type: string
      - description: 商品名称
        in: query
        name: pay_statement
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 微信支付
      tags:
      - 微信
  /auth/refresh:
    get:
      consumes:
      - application/json
      description: Token刷新
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjc1MzIxNjI5OTEsIk5hbWUiOiJhZG1pbiIsIlJvbGUiOm51bGwsIlVzZXJJZCI6MSwiSXNBZG1pbiI6dHJ1ZX0.je9O18vV-E-CENlXnGUk1eztLChZrd9kqsfyCLjg02PE_VNFu6UUlg952qveuJ8yL1yPe-GEdA-FYqMFrqWk1ekQAbDphbO15oD0GpvHZhiTGL3XunNFU_LudLvoOuNEAnEACHxklfMY1J37jesrehhoqxA5pcp0ushINUprsds","message":"success"}'
          schema:
            type: string
      summary: Token刷新
      tags:
      - Token刷新
  /auth/role:
    post:
      consumes:
      - application/json
      description: 角色创建
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 角色名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"message":"ok"}'
          schema:
            type: string
      summary: 角色创建
      tags:
      - 角色
  /auth/role/{id}:
    delete:
      consumes:
      - application/json
      description: 角色删除
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"message":"ok"}'
          schema:
            type: string
      summary: 角色列表
      tags:
      - 角色
    get:
      consumes:
      - application/json
      description: 角色获得
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      - description: 角色名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"message":"ok"}'
          schema:
            type: string
      summary: 角色获得
      tags:
      - 角色
    put:
      consumes:
      - application/json
      description: 角色更新
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      - description: 角色名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"message":"ok"}'
          schema:
            type: string
      summary: 角色更新
      tags:
      - 角色
  /auth/roles:
    get:
      consumes:
      - application/json
      description: 角色列表
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: limit
        type: integer
      - description: 排序
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"message":"ok"}'
          schema:
            type: string
      summary: 角色列表
      tags:
      - 角色
  /auth/self:
    get:
      consumes:
      - application/json
      description: 个人信息获得
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"admin","alias":"","email":"admin@block.vc","password":"","roles":[],"openid":"","active":true,"is_admin":true},"message":"success"}}'
          schema:
            type: string
      summary: 个人信息获得
      tags:
      - 用户
    put:
      consumes:
      - multipart/form-data
      description: 个人信息修改
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"admin","alias":"","email":"admin@block.vc","password":"","roles":[],"openid":"","active":true,"is_admin":true},"message":"success"}}'
          schema:
            type: string
      summary: 个人信息修改
      tags:
      - 用户
  /auth/user/:
    post:
      consumes:
      - multipart/form-data
      description: 用户注册
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"admin","alias":"","email":"admin@block.vc","password":"","roles":[],"openid":"","active":true,"is_admin":true},"message":"success"}}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 用户
  /auth/user/{id}:
    get:
      consumes:
      - application/json
      description: 用户获得,只有管理员才可调用
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"admin","alias":"","email":"admin@block.vc","password":"","roles":[],"openid":"","active":true,"is_admin":true},"message":"success"}}'
          schema:
            type: string
      summary: 用户获得
      tags:
      - 用户
    put:
      consumes:
      - application/json
      description: 用户信息修改,只有管理员才可调用，不修改头像
      parameters:
      - description: 用户信息ID
        in: path
        name: id
        required: true
        type: integer
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"admin","alias":"","email":"admin@block.vc","password":"","roles":[],"openid":"","active":true,"is_admin":true},"message":"success"}}'
          schema:
            type: string
      summary: 用户信息修改
      tags:
      - 用户
  /auth/usermenu:
    get:
      consumes:
      - application/json
      description: 用户菜单树获得
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":[{"id":1,"parent_id":0,"name":"系统设置","route":"route-system","component":"SystemComponent","icon":"system-icon","sequence":1,"children":[{"id":2,"parent_id":1,"name":"系统用户","route":"/system/user","icon":"system-user","sequence":1}]},{"id":3,"parent_id":0,"name":"分类模块","route":"route_modyle","component":"Module","icon":"module","sequence":2,"children":[{"id":4,"parent_id":3,"name":"模块列表","route":"/auth/category","icon":"category","sequence":1}]},{"id":5,"parent_id":0,"name":"公司管理","route":"route_company","component":"Company","icon":"company","sequence":2,"children":[{"id":6,"parent_id":5,"name":"公司分类","route":"route_company_1","component":"Company","icon":"company","sequence":2,"children":[{"id":7,"parent_id":6,"name":"一级公司","route":"route_company_2","component":"Company","icon":"company","sequence":2},{"id":8,"parent_id":6,"name":"二级公司","route":"route_company_3","component":"Company","icon":"company","sequence":2}]}]}],"message":"success"}}'
          schema:
            type: string
      summary: 用户菜单树获得
      tags:
      - 菜单
  /auth/usermenutree/{user_id}:
    get:
      consumes:
      - application/json
      description: 用户菜单树,系统管理员才可用
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":[{"id":1,"parent_id":0,"name":"系统设置","route":"route-system","component":"SystemComponent","icon":"system-icon","sequence":1,"children":[{"id":2,"parent_id":1,"name":"系统用户","route":"/system/user","icon":"system-user","sequence":1}]},{"id":3,"parent_id":0,"name":"分类模块","route":"route_modyle","component":"Module","icon":"module","sequence":2,"children":[{"id":4,"parent_id":3,"name":"模块列表","route":"/auth/category","icon":"category","sequence":1}]},{"id":5,"parent_id":0,"name":"公司管理","route":"route_company","component":"Company","icon":"company","sequence":2,"children":[{"id":6,"parent_id":5,"name":"公司分类","route":"route_company_1","component":"Company","icon":"company","sequence":2,"children":[{"id":7,"parent_id":6,"name":"一级公司","route":"route_company_2","component":"Company","icon":"company","sequence":2},{"id":8,"parent_id":6,"name":"二级公司","route":"route_company_3","component":"Company","icon":"company","sequence":2}]}]}],"message":"success"}}'
          schema:
            type: string
      summary: 用户菜单树
      tags:
      - 菜单
  /auth/users:
    get:
      consumes:
      - application/json
      description: 用户列表，只有管理员才可调用
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":[{"id":1,"name":"admin","alias":"","email":"admin@block.vc","password":"","roles":null,"openid":"","active":true,"is_admin":true},{"id":2,"name":"admin","alias":"","email":"","password":"","roles":null,"openid":"admin","active":true,"is_admin":false}],"message":"success"}'
          schema:
            type: string
      summary: 用户列表
      tags:
      - 用户
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"token":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjc1MzIxNjI5NTQsIk5hbWUiOiJhZG1pbiIsIlJvbGUiOm51bGwsIlVzZXJJZCI6MSwiSXNBZG1pbiI6dHJ1ZX0.YzPovX4xP6PPlZV9UGPKWgoLfGL8hnnC01j3L-k6f56mJuds7UDL--3Nts_P6RhuOQgzv7BL7hh6CJdSJdopjzE4A4HmEsq80_DN7cazuFE6gzA2ZfVLI7jslnWcJmVHVPTfu8_57NScdfxCDX_nFbbZUWjzDy7iT5L5zLXrBvg","user":{"id":1,"name":"admin","alias":"","email":"admin@block.vc","password":"","roles":[],"openid":"","active":true,"is_admin":true}},"message":"success"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户登录
  /login/wechat:
    post:
      consumes:
      - application/json
      description: 用户微信登录
      parameters:
      - description: 微信openid
        in: query
        name: openid
        required: true
        type: string
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 用户头像
        in: query
        name: head
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"token":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjc1MzIxNjMwODMsIk5hbWUiOiJhZG1pbiIsIlJvbGUiOm51bGwsIlVzZXJJZCI6MiwiSXNBZG1pbiI6ZmFsc2V9.HZq5jBw4-ZQipQPnq0K7Ei0_LvaRXZGNgKqLoFnhV_vpfQupmddsDMZbiI_Yy0Zhd7J7AvRGDXMfVwW9-TidsDrux6-L4KQWIV0Mrlj4SXgW13HvMSXW0XzHYQBxiai61AeJx4VmQR84s2lI5hmKuiVOpsyOZAduJoO1K26b8X4","user":{"id":2,"name":"admin","alias":"","email":"","password":"","roles":[],"openid":"admin","active":true,"is_admin":false}},"message":"success"}'
          schema:
            type: string
      summary: 用户微信登录
      tags:
      - 用户登录
swagger: "2.0"
